image: python:3

pipelines:
  branches:
    master:
      - step:
          deployment : production
          script:
            - pip install -r requirements.txt
            - ./scripts/code-coverage.sh
            - echo $BITBUCKET_COMMIT > release
